### ISSUE TITLE
Failed to convert archive format pack to FS format

### ISSUE THREAD

**Issue by eldudi** [marian-m12l/studio#196]
Hi!

I have created a pack with Studio and I tried to put it in my Lunii.
I got this error message below. I guess I am not the only one after having checked a little bit on internet.

I have verified all the assets and all the images and audio files are with good format.
I really don't know what's hapenning there. 
Can anyone help please ?

2021-05-11 08:47:06,736 [ERROR] [s.w.s.LibraryService]: Failed to convert archive format pack to FS format
java.nio.file.DirectoryNotEmptyException: D:\Temp\Gabin_et_Clementine-bda52485-2c3c-4633-ac17-767c10739d8f-v1.zip5648666837633001794\10739D8F
        at java.base/sun.nio.fs.WindowsFileCopy.ensureEmptyDir(WindowsFileCopy.java:264)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:427)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.move(Files.java:1426)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "Timer-0" java.lang.RuntimeException: Failed to convert archive format pack to FS format
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:319)
        at studio.webui.api.LibraryController$2.run(LibraryController.java:103)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: **java.nio.file.DirectoryNotEmptyException: D:\Temp\**Gabin_et_Clementine-bda52485-2c3c-4633-ac17-767c10739d8f-v1.zip5648666837633001794\10739D8F
        at java.base/sun.nio.fs.WindowsFileCopy.ensureEmptyDir(WindowsFileCopy.java:264)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:427)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.move(Files.java:1426)
        at studio.webui.service.LibraryService.addConvertedFsPackFile(LibraryService.java:314)
        ... 3 more

**Comment by marian-m12l** [comment]
@eldudi Thanks for the feedback. This should be fixed with the latest version.

**Comment by ymmx2** [comment]
It got the same issue with the version 0.3.1. How can I pass by this issue?

**Comment by LeBuzzy** [comment]
This exception is still present in 0.3.1..Can you just put a try catch in that section and handle that exception ?
